package com.zym.memorymaster.dao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zym.memorymaster.dao.entities.LocalBookContent;

import com.zym.memorymaster.dao.greendao.LocalBookContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localBookContentDaoConfig;

    private final LocalBookContentDao localBookContentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localBookContentDaoConfig = daoConfigMap.get(LocalBookContentDao.class).clone();
        localBookContentDaoConfig.initIdentityScope(type);

        localBookContentDao = new LocalBookContentDao(localBookContentDaoConfig, this);

        registerDao(LocalBookContent.class, localBookContentDao);
    }
    
    public void clear() {
        localBookContentDaoConfig.clearIdentityScope();
    }

    public LocalBookContentDao getLocalBookContentDao() {
        return localBookContentDao;
    }

}
